### PR TITLE
Fixing the 'max_per_page' issue

### PR DESCRIPTION
**Pull request by Bastes**
Hey ^^ thanks for fixing https://github.com/randym/activeadmin-axlsx/issues/42#issuecomment-231183050 ; there remained an issue though, which this patch fixes (at least on my build). Inspired from: https://github.com/thambley/activeadmin-xls/issues/2

Hope you like it ^^

### CODE REVIEW

**Comment by ybart** [comment]
I'm no longer using this fork. However, I'm happy to merge it if it helps.

**Comment by Bastes** [comment]
Well, now you're mentionning it... which fork are all the people using actually? (since it's apparent the original gem is not maintained anymore)

**Comment by ybart** [comment]
Unfortunately, it looks like nobody is actively maintaining it.

**Comment by Bastes** [comment]
I meant, you mentionned you're no longer using this fork ; I supposed it meant you're using another and was curious as to which ^^°

**Comment by ybart** [comment]
In fact I am now working on an other project and no longer using the gem at all. But I believe my previous company might still use it.

**Comment by Bastes** [comment]
Oh, well ^^° thanks for your help.

**Pull request merged**
